# Generated by Django 3.2.6 on 2021-09-09 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bills_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='automaticPayment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bills',
            name='dueDate',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
